### ISSUE TITLE
Publishing to Repos

### ISSUE THREAD

**Issue by dingwa** [openzipkin/brave-opentracing#1]
Listed on the maven pom.xml file is the URL for the jar http://oss.jfrog.org/oss-snapshot-local/io/opentracing/brave.  However there is no associated jars listed in this location.

Could we please have this published?

**Comment by adriancole** [comment]
this should be a start. once merged snapshots should work https://github.com/openzipkin/brave-opentracing/pull/2

**Comment by adriancole** [comment]
I need to re-encrypt the travis credentials..

**Comment by adriancole** [comment]
encrypted my credentials for this.. https://github.com/openzipkin/brave-opentracing/commit/7b4ff01082d4860ad12172f5a6f17c231c9f0d25

**Comment by adriancole** [comment]
voilla http://oss.jfrog.org/oss-snapshot-local/io/opentracing/brave/brave-opentracing/0.15.0-SNAPSHOT/

**Comment by adriancole** [comment]
I'll publish a 0.15 version just to test things

**Comment by adriancole** [comment]
ignore the patch qualification. I'm aware it isn't important in <1.0 releases, just don't want to allocate time to figure out if scripts need a change to omit it.

```bash
$ git tag release-0.15.0
$ git push origin release-0.15.0
```

**Comment by adriancole** [comment]
done!

https://bintray.com/opentracing/maven/opentracing-brave/0.15.0#central

**Comment by dingwa** [comment]
Brilliant! Thanks I'll give it a go now
