### ISSUE TITLE
dapper&opentracing

### ISSUE THREAD

**Issue by yzfshuijing** [openzipkin/brave-opentracing#22]
I have a question, zipkin is based on dapper, and cs,cr,ss,sr have the same spanid.  But in opentracing, cs,cr and ss,sr do not have the same span id ,and they have a child of relationship. Is that may have some influence？
Looking forward for your answer！

**Comment by adriancole** [comment]
opentracing does not define how to represent remote operations, so what you
are mentioning is how some choose to do it (or perhaps example code), right?

zipkin predates OT by a while, and its data model was written for RPCs
sharing span for client and server. That said, you'll notice
zipkin-go-opentracing has a flag on how to handle remote spans (ex shared
span or not).

Regardless, there's still work needed to support a single-host model, and
the primary driver for this work is OT which while doesn't explicitly
require single-host spans, in practice, many assume it.

https://github.com/openzipkin/zipkin/issues/1480

**Comment by yzfshuijing** [comment]
thanks for your answer, in brave-opentracing, 
public final Span joinSpan(TraceContext context) , public Span newTrace(SamplingFlags samplingFlags) 
the above two functions 
 so in remote operations, if i want to use the same span, i can just use joinSpan, if not just use newTrace.
is that right?

**Comment by adriancole** [comment]
actually, you'd want to use `newChild` as `newTrace` should only be used when an existing trace can't be read (as it restarts a trace) cc @reta

**Comment by yzfshuijing** [comment]
oh i see, thanks so much
