### ISSUE TITLE
Active span propagation issue

### ISSUE THREAD

**Issue by tutufool** [openzipkin/brave-opentracing#48]
Hi,

I just found:
  public static final class Default extends CurrentTraceContext {
    // static as we want one context per thread, not one context per thread-instance.
    // if this is not static, patterns that coordinate via statics (like Tracer.current()) will break.
    // static ThreadLocal was also used in Brave 3's ThreadLocalServerClientAndLocalSpanState
    static final **InheritableThreadLocal**<TraceContext> local = new InheritableThreadLocal<>();

So if I have code like:

try(ActiveSpan span = tracer.buildSpan(...).startActive()){

 //some code could create new thread and there's biz logic in the newly created thread which will access tracer.activeSpan()
}

I've a little worry that the span gets leaked to child thread and no one will deactivate it.

Considering the piece of code is not under my control, and I can NOT go with the Continuation solution.
(Some 3rd party lib might create sub threads on the fly)

Let me know if this is a valid concern.

Thanks
Leon

**Comment by adriancole** [comment]
This is a valid concern. The current workaround is be to copy/paste the
20lines of CurrentTraceContext.Default into your own class that doesn't use
an inheritable thread local. The design of CurrentTraceContext was
intentionally made to require very little code to implement, for reasons
such as these.

**Comment by tutufool** [comment]
Got it, Thanks a lot!

**Comment by adriancole** [comment]
https://github.com/openzipkin/brave/pull/470 should fix this
