### ISSUE TITLE
Parent Span is overwritten by children span

### ISSUE THREAD

**Issue by jerryjxj** [openzipkin/brave-opentracing#7]
Use the example code in README, the second span will overwrite the previous span.
Root cause: The saving point is at **AbstractSpan.close()**, only ThreadLocalServerClientAndLocalSpanState.**currentLocalSpan** is saved. It is ThreadLocal. So only the **last** local span is saved.

The same issue might occurs in *currentClientSpan* and *currentServerSpan*.

May refer to implementation of spring.cloud.sleuth

**Comment by zmzheng** [comment]
It seems that InheritableServerClientAndLocalSpanState is needed in order to get nested spans work.

**Comment by jerryjxj** [comment]
@zmzheng InheritableServerClientAndLocalSpanState partially works. 

But it does not work properly in following fork-join senario:
1. Create span A,
2. Create span B (Parent is A) in sub-thread B.
3. Create span C (parent is A) in sub-thread C.

You may find span C is a child of span B sometimes.

**Comment by michaelsembwever** [comment]
See https://github.com/openzipkin/brave-opentracing/pull/11

Have gone with the simpler InheritableServerClientAndLocalSpanState solution for now.

A more robust approach should be done in conjunction with a rewrite to use zipkin-reporter-java¹

¹ https://github.com/openzipkin/zipkin-reporter-java

**Comment by adriancole** [comment]
I'm near positive this issue is unrelated to the current code, both from brave and opentracing sides. feel free to reopen
